// langur/bytecode/bytecode.go

package bytecode

import (
	"langur/object"
)

// ByteCode struct in a separate package to untangle dependencies
// built by compiler; used by VM

var LangurRev = "0.17.3-dev"

// to pass from compiler to VM
type ByteCode struct {
	StartCode *object.CompiledCode
	Constants []object.Object

	// global late-binding assignments for the VM to fill in (opcodes already generated by Compiler)
	Late []string

	// for tracing errors back to source
	Source string
}
