// langur/bytecode/bytecode.go

package bytecode

import (
	"langur/object"
)

// in a separate package to untangle dependencies

const LangurRev = "0.16.3"

// to pass from compiler to VM
type ByteCode struct {
	StartCode *object.CompiledCode
	Constants []object.Object

	// global late-binding assignments for the VM to fill in (opcodes already generated by Compiler)
	Late []string
}
